language: r
r:
  - oldrel
  - release
  - devel
r_packages:
  - testthat
r_github_packages:
  - jimhester/covr
cache: packages
sudo: false
addons:
  apt:
    packages:
      - libnetcdf-dev
      - netcdf-bin
after_success:
  - Rscript -e 'covr::coveralls()'